import type { Question } from "./types";

export const QUESTIONS: Question[] = [
  // ===== MATH: LINEAR EQUATIONS =====
  {
    id: "m001", section: "math", topic: "linear", difficulty: "easy",
    question: "If 4x − 9 = 2x + 7, what is the value of x?",
    options: ["−1", "2", "8", "16"],
    answer: 2,
    explanation: "Subtract 2x from both sides: 2x − 9 = 7. Add 9: 2x = 16. Divide by 2: x = 8.",
  },
  {
    id: "m002", section: "math", topic: "linear", difficulty: "medium",
    question: "A taxi charges a $2.50 flat fee plus $0.75 per mile. If a ride costs $11.50, how many miles was the ride?",
    options: ["8", "12", "14", "16"],
    answer: 1,
    explanation: "Set up: 2.50 + 0.75m = 11.50 → 0.75m = 9 → m = 12 miles.",
  },
  {
    id: "m003", section: "math", topic: "linear", difficulty: "medium",
    question: "Company A rents cars for $40 + $0.15 per mile. Company B charges $25 + $0.20 per mile. For how many miles do both companies charge the same amount?",
    options: ["100", "200", "300", "400"],
    answer: 2,
    explanation: "Set equal: 40 + 0.15m = 25 + 0.20m → 15 = 0.05m → m = 300 miles.",
  },
  {
    id: "m004", section: "math", topic: "linear", difficulty: "hard",
    question: "A venue sells adult tickets for $12 and student tickets for $7. A total of 80 tickets were sold for $735. How many student tickets were sold?",
    options: ["31", "35", "41", "45"],
    answer: 3,
    explanation: "Let s = student tickets, a = 80 − s. Then 12(80 − s) + 7s = 735 → 960 − 5s = 735 → s = 45.",
  },

  {
    id: "m031", section: "math", topic: "linear", difficulty: "easy",
    question: "If 3x + 5 = 20, what is the value of x?",
    options: ["3", "5", "7", "9"],
    answer: 1,
    explanation: "Subtract 5 from both sides: 3x = 15. Divide by 3: x = 5.",
  },
  {
    id: "m032", section: "math", topic: "linear", difficulty: "medium",
    question: "A gym charges a $30 signup fee plus $15 per month. If the total cost after m months is $135, what is m?",
    options: ["5", "6", "7", "8"],
    answer: 2,
    explanation: "Set up: 30 + 15m = 135 → 15m = 105 → m = 7.",
  },
  {
    id: "m033", section: "math", topic: "linear", difficulty: "medium",
    question: "Company X sells notebooks for $4 each plus a $10 flat shipping fee. Company Y sells notebooks for $3.50 each plus a $15 flat shipping fee. For how many notebooks is the total cost the same at both companies?",
    options: ["5", "8", "10", "12"],
    answer: 2,
    explanation: "Set 4n + 10 = 3.5n + 15. Subtract 3.5n: 0.5n + 10 = 15 → 0.5n = 5 → n = 10.",
  },
  {
    id: "m034", section: "math", topic: "linear", difficulty: "hard",
    question: "A phone plan costs $20 per month plus $0.10 per text message. Another plan costs a flat $35 with unlimited texts. For how many texts do the two plans cost the same amount?",
    options: ["100", "120", "150", "200"],
    answer: 2,
    explanation: "Set 20 + 0.10t = 35 → 0.10t = 15 → t = 150.",
  },
  {
    id: "m035", section: "math", topic: "linear", difficulty: "easy",
    question: "If 2(x + 3) = 16, what is the value of x?",
    options: ["4", "5", "6", "7"],
    answer: 1,
    explanation: "Distribute: 2x + 6 = 16 → 2x = 10 → x = 5.",
  },
  {
    id: "m036", section: "math", topic: "linear", difficulty: "medium",
    question: "The perimeter of a rectangle is 54. The length is 3 more than twice the width. What is the width?",
    options: ["6", "7", "8", "9"],
    answer: 2,
    explanation: "Perimeter: 2(l + w) = 54 → l + w = 27. Since l = 2w + 3: (2w + 3) + w = 27 → 3w = 24 → w = 8.",
  },
  {
    id: "m037", section: "math", topic: "linear", difficulty: "medium",
    question: "A rope 100 feet long is cut into two pieces so that one piece is 20 feet longer than the other. What is the length of the shorter piece?",
    options: ["30", "35", "40", "45"],
    answer: 2,
    explanation: "Let the shorter piece be x. Then x + (x + 20) = 100 → 2x = 80 → x = 40.",
  },
  {
    id: "m038", section: "math", topic: "linear", difficulty: "hard",
    question: "Working alone, Ana can paint a fence in 6 hours. Working alone, Bo can paint the same fence in 3 hours. If they work together at their individual rates, how many hours will it take them to paint the fence?",
    options: ["1.5", "2", "2.5", "3"],
    answer: 1,
    explanation: "Combined rate = 1/6 + 1/3 = 1/6 + 2/6 = 3/6 = 1/2 fence per hour. Time = 1 ÷ (1/2) = 2 hours.",
  },
  {
    id: "m039", section: "math", topic: "linear", difficulty: "easy",
    question: "If 5x − 3 = 3x + 11, what is the value of x?",
    options: ["5", "6", "7", "8"],
    answer: 2,
    explanation: "Subtract 3x from both sides: 2x − 3 = 11. Add 3: 2x = 14. Divide by 2: x = 7.",
  },
  {
    id: "m040", section: "math", topic: "linear", difficulty: "medium",
    question: "Adult tickets cost $9 and child tickets cost $6. A group of 10 people paid $78 total. How many children were in the group?",
    options: ["2", "3", "4", "5"],
    answer: 2,
    explanation: "Let c = children, a = adults. a + c = 10 and 9a + 6c = 78. Since a = 10 − c: 9(10 − c) + 6c = 78 → 90 − 3c = 78 → c = 4.",
  },

  // ===== MATH: SYSTEMS OF EQUATIONS =====
  {
    id: "m005", section: "math", topic: "systems", difficulty: "easy",
    question: "If 3x + y = 11 and x − y = 1, what is the value of x?",
    options: ["1", "2", "3", "4"],
    answer: 2,
    explanation: "Add the equations: 4x = 12, so x = 3.",
  },
  {
    id: "m006", section: "math", topic: "systems", difficulty: "medium",
    question: "At a bakery, 2 muffins and 3 cookies cost $8.50. Four muffins and 1 cookie cost $9.50. What does one cookie cost?",
    options: ["$1.00", "$1.50", "$2.00", "$2.50"],
    answer: 1,
    explanation: "Multiply equation 1 by 2: 4m + 6c = 17. Subtract equation 2: 5c = 7.50 → c = $1.50.",
  },
  {
    id: "m007", section: "math", topic: "systems", difficulty: "medium",
    question: "Marcus is 3 times as old as his sister. In 4 years, Marcus will be twice as old as his sister. How old is Marcus now?",
    options: ["4", "8", "12", "16"],
    answer: 2,
    explanation: "Let s = sister's age, Marcus = 3s. In 4 years: 3s + 4 = 2(s + 4) → s = 4. Marcus = 3(4) = 12.",
  },
  {
    id: "m008", section: "math", topic: "systems", difficulty: "medium",
    question: "Two numbers have a sum of 45 and a difference of 13. What is the larger number?",
    options: ["13", "16", "22", "29"],
    answer: 3,
    explanation: "x + y = 45 and x − y = 13. Add: 2x = 58 → x = 29.",
  },

  {
    id: "m041", section: "math", topic: "systems", difficulty: "easy",
    question: "If x + y = 10 and x − y = 4, what is the value of x?",
    options: ["5", "6", "7", "8"],
    answer: 2,
    explanation: "Add the equations: 2x = 14, so x = 7.",
  },
  {
    id: "m042", section: "math", topic: "systems", difficulty: "medium",
    question: "2 pens and 3 notebooks cost $12. 1 pen and 2 notebooks cost $7. What does one pen cost?",
    options: ["$2", "$3", "$4", "$5"],
    answer: 1,
    explanation: "From the second equation, p = 7 − 2n. Substitute into the first: 2(7 − 2n) + 3n = 12 → 14 − n = 12 → n = 2, so p = 7 − 4 = 3.",
  },
  {
    id: "m043", section: "math", topic: "systems", difficulty: "medium",
    question: "Two numbers have a sum of 50. Twice the smaller number equals 10 more than the larger number. What is the smaller number?",
    options: ["15", "18", "20", "22"],
    answer: 2,
    explanation: "Let x be smaller, y larger: x + y = 50 and 2x = y + 10. Substitute y = 50 − x: 2x = 50 − x + 10 → 3x = 60 → x = 20.",
  },
  {
    id: "m044", section: "math", topic: "systems", difficulty: "hard",
    question: "At a bake sale, cupcakes sell for $2 and cookies sell for $1. A total of 45 items were sold for $75. How many cupcakes were sold?",
    options: ["25", "28", "30", "32"],
    answer: 2,
    explanation: "Let c = cupcakes, k = cookies. c + k = 45 and 2c + k = 75. Subtracting the first from the second: c = 30.",
  },
  {
    id: "m045", section: "math", topic: "systems", difficulty: "easy",
    question: "If 3x + y = 10 and y = 2x, what is the value of x?",
    options: ["1", "2", "3", "4"],
    answer: 1,
    explanation: "Substitute y = 2x: 3x + 2x = 10 → 5x = 10 → x = 2.",
  },
  {
    id: "m046", section: "math", topic: "systems", difficulty: "medium",
    question: "The sum of two numbers is 24 and their difference is 6. What is the product of the two numbers?",
    options: ["108", "120", "135", "144"],
    answer: 2,
    explanation: "x + y = 24 and x − y = 6. Adding: 2x = 30 → x = 15, so y = 9. Product = 15 × 9 = 135.",
  },
  {
    id: "m047", section: "math", topic: "systems", difficulty: "medium",
    question: "A store sold 60 shirts, some at $20 and some at $12, for total revenue of $920. How many $20 shirts were sold?",
    options: ["20", "22", "25", "28"],
    answer: 2,
    explanation: "Let a = $20 shirts, b = $12 shirts. a + b = 60 and 20a + 12b = 920. Since b = 60 − a: 20a + 12(60 − a) = 920 → 8a + 720 = 920 → a = 25.",
  },
  {
    id: "m048", section: "math", topic: "systems", difficulty: "hard",
    question: "Line 1 passes through (0, 4) and (2, 10). Line 2 passes through (0, −2) and (4, 6). At what x-value do the lines intersect?",
    options: ["-8", "-6", "-4", "-2"],
    answer: 1,
    explanation: "Line 1: slope = (10−4)/2 = 3, so y = 3x + 4. Line 2: slope = (6−(−2))/4 = 2, so y = 2x − 2. Setting equal: 3x + 4 = 2x − 2 → x = −6.",
  },

  // ===== MATH: QUADRATICS =====
  {
    id: "m009", section: "math", topic: "quadratics", difficulty: "easy",
    question: "What are the solutions to x² − 5x + 6 = 0?",
    options: ["x = 1 and x = 6", "x = 2 and x = 3", "x = −2 and x = −3", "x = −1 and x = 6"],
    answer: 1,
    explanation: "Factor: (x − 2)(x − 3) = 0, so x = 2 or x = 3.",
  },
  {
    id: "m010", section: "math", topic: "quadratics", difficulty: "hard",
    question: "A ball is launched upward. Its height h (in feet) at time t seconds is h = −16t² + 48t + 5. What is the maximum height the ball reaches?",
    options: ["32 ft", "37 ft", "41 ft", "53 ft"],
    answer: 2,
    explanation: "Vertex at t = 48/(2×16) = 1.5 s. h(1.5) = −16(2.25) + 48(1.5) + 5 = −36 + 72 + 5 = 41 ft.",
  },
  {
    id: "m011", section: "math", topic: "quadratics", difficulty: "medium",
    question: "The product of two consecutive positive integers is 56. What is the greater integer?",
    options: ["6", "8", "9", "14"],
    answer: 1,
    explanation: "n(n + 1) = 56 → n² + n − 56 = 0 → (n − 7)(n + 8) = 0 → n = 7. Greater integer = 8.",
  },
  {
    id: "m012", section: "math", topic: "quadratics", difficulty: "medium",
    question: "Which of the following is a factor of x² + 6x + 5?",
    options: ["x + 2", "x + 3", "x + 5", "x − 1"],
    answer: 2,
    explanation: "Factor: x² + 6x + 5 = (x + 1)(x + 5). So (x + 5) is a factor.",
  },

  {
    id: "m049", section: "math", topic: "quadratics", difficulty: "easy",
    question: "What are the solutions to x² − 9 = 0?",
    options: ["x = 3 only", "x = −3 only", "x = 3 and x = −3", "x = 9 and x = −9"],
    answer: 2,
    explanation: "x² = 9, so x = 3 or x = −3.",
  },
  {
    id: "m050", section: "math", topic: "quadratics", difficulty: "medium",
    question: "The equation x² + 4x − 12 = 0 has two solutions. What is their sum?",
    options: ["-4", "-2", "2", "4"],
    answer: 0,
    explanation: "For ax² + bx + c = 0, the sum of the roots equals −b/a = −4/1 = −4.",
  },
  {
    id: "m051", section: "math", topic: "quadratics", difficulty: "medium",
    question: "If (x − 4)(x + 2) = 0, what is the greater solution for x?",
    options: ["-4", "-2", "2", "4"],
    answer: 3,
    explanation: "The solutions are x = 4 and x = −2. The greater one is 4.",
  },
  {
    id: "m052", section: "math", topic: "quadratics", difficulty: "hard",
    question: "A rectangle's length is 3 more than its width. If its area is 40, what is the width?",
    options: ["4", "5", "6", "7"],
    answer: 1,
    explanation: "w(w + 3) = 40 → w² + 3w − 40 = 0 → (w − 5)(w + 8) = 0. Since width is positive, w = 5.",
  },
  {
    id: "m053", section: "math", topic: "quadratics", difficulty: "medium",
    question: "A ball's height is modeled by h(t) = −16t² + 32t. What is the maximum height the ball reaches?",
    options: ["8", "12", "16", "20"],
    answer: 2,
    explanation: "Vertex at t = −b/2a = 32/32 = 1. h(1) = −16 + 32 = 16.",
  },
  {
    id: "m054", section: "math", topic: "quadratics", difficulty: "easy",
    question: "Which of the following is equivalent to x² − 6x + 9?",
    options: ["(x − 3)²", "(x + 3)²", "(x − 9)²", "x(x − 6)"],
    answer: 0,
    explanation: "x² − 6x + 9 factors as (x − 3)(x − 3) = (x − 3)².",
  },
  {
    id: "m055", section: "math", topic: "quadratics", difficulty: "hard",
    question: "The product of two consecutive positive even integers is 168. What is the smaller integer?",
    options: ["10", "12", "14", "16"],
    answer: 1,
    explanation: "Let n and n+2 be the integers. n(n+2) = 168 → n² + 2n − 168 = 0 → (n−12)(n+14) = 0. Since n is positive, n = 12.",
  },
  {
    id: "m056", section: "math", topic: "quadratics", difficulty: "medium",
    question: "What are the solutions to 2x² − 8x + 6 = 0?",
    options: ["x = 1 and x = 3", "x = -1 and x = -3", "x = 2 and x = 3", "x = 1 and x = 6"],
    answer: 0,
    explanation: "Divide by 2: x² − 4x + 3 = 0 → (x − 1)(x − 3) = 0 → x = 1 or x = 3.",
  },

  // ===== MATH: FUNCTIONS =====
  {
    id: "m013", section: "math", topic: "functions", difficulty: "easy",
    question: "If f(x) = 3x² − 2x + 1, what is f(−2)?",
    options: ["7", "9", "17", "21"],
    answer: 2,
    explanation: "f(−2) = 3(4) − 2(−2) + 1 = 12 + 4 + 1 = 17.",
  },
  {
    id: "m014", section: "math", topic: "functions", difficulty: "medium",
    question: "The function g is defined by g(x) = 2x + k, where k is a constant. If g(3) = 11, what is g(−1)?",
    options: ["−3", "1", "3", "7"],
    answer: 2,
    explanation: "g(3) = 6 + k = 11 → k = 5. g(−1) = −2 + 5 = 3.",
  },
  {
    id: "m015", section: "math", topic: "functions", difficulty: "medium",
    question: "If f(x) = x² and g(x) = 3x − 2, what is f(g(2))?",
    options: ["4", "8", "16", "36"],
    answer: 2,
    explanation: "g(2) = 6 − 2 = 4. f(4) = 4² = 16.",
  },
  {
    id: "m016", section: "math", topic: "functions", difficulty: "easy",
    question: "For what value of x is the function h(x) = x / (x − 3) undefined?",
    options: ["x = 0", "x = 3", "x = −3", "h(x) is defined for all x"],
    answer: 1,
    explanation: "h(x) is undefined when the denominator equals zero: x − 3 = 0 → x = 3.",
  },

  {
    id: "m057", section: "math", topic: "functions", difficulty: "easy",
    question: "If f(x) = 2x + 5, what is f(3)?",
    options: ["8", "9", "10", "11"],
    answer: 3,
    explanation: "f(3) = 2(3) + 5 = 6 + 5 = 11.",
  },
  {
    id: "m058", section: "math", topic: "functions", difficulty: "medium",
    question: "If f(x) = x² − 4 and f(a) = 12, what is a positive value of a?",
    options: ["2", "3", "4", "5"],
    answer: 2,
    explanation: "a² − 4 = 12 → a² = 16 → a = 4 (taking the positive value).",
  },
  {
    id: "m059", section: "math", topic: "functions", difficulty: "medium",
    question: "The function g is defined by g(x) = 4x − 7. If g(k) = 9, what is k?",
    options: ["2", "3", "4", "5"],
    answer: 2,
    explanation: "4k − 7 = 9 → 4k = 16 → k = 4.",
  },
  {
    id: "m060", section: "math", topic: "functions", difficulty: "hard",
    question: "If f(x) = 2x + 1 and g(x) = x − 3, what is f(g(5))?",
    options: ["3", "4", "5", "6"],
    answer: 2,
    explanation: "g(5) = 5 − 3 = 2. f(2) = 2(2) + 1 = 5.",
  },
  {
    id: "m061", section: "math", topic: "functions", difficulty: "easy",
    question: "For h(x) = 5 / (x + 2), for what value of x is h(x) undefined?",
    options: ["-5", "-2", "0", "2"],
    answer: 1,
    explanation: "h(x) is undefined when the denominator is 0: x + 2 = 0 → x = −2.",
  },
  {
    id: "m062", section: "math", topic: "functions", difficulty: "medium",
    question: "If f(x) = 3x² and f(a) = 48, what is a positive value of a?",
    options: ["2", "3", "4", "5"],
    answer: 2,
    explanation: "3a² = 48 → a² = 16 → a = 4 (taking the positive value).",
  },
  {
    id: "m063", section: "math", topic: "functions", difficulty: "hard",
    question: "The function p(x) = x² − 2x + k has a minimum value of 5. What is k?",
    options: ["4", "5", "6", "7"],
    answer: 2,
    explanation: "The vertex occurs at x = −b/2a = 2/2 = 1. p(1) = 1 − 2 + k = k − 1. Setting k − 1 = 5 gives k = 6.",
  },
  {
    id: "m064", section: "math", topic: "functions", difficulty: "medium",
    question: "If f(x) = 2^x, what is f(3) − f(1)?",
    options: ["4", "6", "8", "10"],
    answer: 1,
    explanation: "f(3) = 8 and f(1) = 2. 8 − 2 = 6.",
  },

  // ===== MATH: GEOMETRY =====
  {
    id: "m017", section: "math", topic: "geometry", difficulty: "easy",
    question: "In a right triangle, one leg has length 5 and the hypotenuse has length 13. What is the length of the other leg?",
    options: ["8", "10", "11", "12"],
    answer: 3,
    explanation: "By the Pythagorean theorem: 5² + b² = 13² → 25 + b² = 169 → b² = 144 → b = 12.",
  },
  {
    id: "m018", section: "math", topic: "geometry", difficulty: "medium",
    question: "A circle has a circumference of 20π. What is its area?",
    options: ["10π", "40π", "100π", "400π"],
    answer: 2,
    explanation: "C = 2πr = 20π → r = 10. Area = πr² = π(100) = 100π.",
  },
  {
    id: "m019", section: "math", topic: "geometry", difficulty: "medium",
    question: "Two parallel lines are cut by a transversal. One co-interior (same-side interior) angle measures 65°. What is the measure of the other co-interior angle?",
    options: ["65°", "115°", "125°", "180°"],
    answer: 1,
    explanation: "Co-interior angles are supplementary (add to 180°): 180° − 65° = 115°.",
  },
  {
    id: "m020", section: "math", topic: "geometry", difficulty: "medium",
    question: "In right triangle ABC (right angle at C), sin(A) = 3/5. What is cos(A)?",
    options: ["3/4", "4/5", "5/3", "5/4"],
    answer: 1,
    explanation: "If sin(A) = 3/5, then opposite = 3, hypotenuse = 5, so adjacent = √(25 − 9) = 4. cos(A) = 4/5.",
  },
  {
    id: "m021", section: "math", topic: "geometry", difficulty: "medium",
    question: "What is the distance between points (1, 4) and (5, 1)?",
    options: ["3", "4", "5", "7"],
    answer: 2,
    explanation: "d = √((5−1)² + (1−4)²) = √(16 + 9) = √25 = 5.",
  },
  {
    id: "m030", section: "math", topic: "geometry", difficulty: "easy",
    question: "A square has a perimeter of 24. What is its area?",
    options: ["6", "24", "36", "144"],
    answer: 2,
    explanation: "Perimeter = 4s = 24 → s = 6. Area = s² = 36.",
  },

  {
    id: "m065", section: "math", topic: "geometry", difficulty: "easy",
    question: "A right triangle has legs of length 6 and 8. What is the length of the hypotenuse?",
    options: ["9", "10", "11", "12"],
    answer: 1,
    explanation: "By the Pythagorean theorem: √(6² + 8²) = √(36 + 64) = √100 = 10.",
  },
  {
    id: "m066", section: "math", topic: "geometry", difficulty: "medium",
    question: "A rectangle has length 12 and width 5. What is the length of its diagonal?",
    options: ["12", "13", "14", "15"],
    answer: 1,
    explanation: "The diagonal is the hypotenuse of a right triangle with legs 12 and 5: √(144 + 25) = √169 = 13.",
  },
  {
    id: "m067", section: "math", topic: "geometry", difficulty: "medium",
    question: "A circle has an area of 49π. What is its circumference?",
    options: ["7π", "10π", "14π", "49π"],
    answer: 2,
    explanation: "Area = πr² = 49π → r² = 49 → r = 7. Circumference = 2πr = 14π.",
  },
  {
    id: "m068", section: "math", topic: "geometry", difficulty: "easy",
    question: "In a triangle, two angles measure 50° and 65°. What is the measure of the third angle?",
    options: ["55°", "60°", "65°", "70°"],
    answer: 2,
    explanation: "The angles of a triangle sum to 180°: 180 − 50 − 65 = 65°.",
  },
  {
    id: "m069", section: "math", topic: "geometry", difficulty: "medium",
    question: "Two similar rectangles have corresponding sides in a ratio of 3:4. If the smaller rectangle's area is 27, what is the larger rectangle's area?",
    options: ["36", "42", "48", "54"],
    answer: 2,
    explanation: "Area ratio = (side ratio)² = (3/4)² = 9/16. Larger area = 27 × (16/9) = 48.",
  },
  {
    id: "m070", section: "math", topic: "geometry", difficulty: "hard",
    question: "A right triangle has an area of 24 and one leg of length 6. What is the length of the hypotenuse?",
    options: ["8", "9", "10", "11"],
    answer: 2,
    explanation: "Area = ½ × 6 × b = 24 → b = 8. Hypotenuse = √(6² + 8²) = √100 = 10.",
  },
  {
    id: "m071", section: "math", topic: "geometry", difficulty: "medium",
    question: "In right triangle ABC (right angle at C), tan(A) = 5/12. What is sin(A)?",
    options: ["5/13", "12/13", "5/12", "12/5"],
    answer: 0,
    explanation: "If tan(A) = 5/12, the opposite side is 5 and adjacent is 12, so the hypotenuse is √(25+144) = 13. sin(A) = opposite/hypotenuse = 5/13.",
  },
  {
    id: "m072", section: "math", topic: "geometry", difficulty: "easy",
    question: "A cube has a volume of 64 cubic units. What is the length of one edge?",
    options: ["3", "4", "5", "6"],
    answer: 1,
    explanation: "Volume = s³ = 64 → s = ∛64 = 4.",
  },
  {
    id: "m073", section: "math", topic: "geometry", difficulty: "medium",
    question: "What is the distance between the points (−2, 3) and (4, −5)?",
    options: ["8", "9", "10", "11"],
    answer: 2,
    explanation: "d = √((4−(−2))² + (−5−3)²) = √(36 + 64) = √100 = 10.",
  },
  {
    id: "m074", section: "math", topic: "geometry", difficulty: "hard",
    question: "A sector of a circle with radius 6 has a central angle of 60°. What is the area of the sector?",
    options: ["3π", "4π", "6π", "12π"],
    answer: 2,
    explanation: "Sector area = (60/360) × π × 6² = (1/6) × 36π = 6π.",
  },

  // ===== MATH: STATISTICS =====
  {
    id: "m022", section: "math", topic: "statistics", difficulty: "medium",
    question: "The mean of five numbers is 14. Four of the numbers are 8, 12, 18, and 20. What is the fifth number?",
    options: ["8", "12", "14", "16"],
    answer: 1,
    explanation: "Total sum = 5 × 14 = 70. Known sum = 8 + 12 + 18 + 20 = 58. Fifth number = 70 − 58 = 12.",
  },
  {
    id: "m023", section: "math", topic: "statistics", difficulty: "easy",
    question: "A bag contains 4 red, 3 blue, and 5 green marbles. If one marble is drawn at random, what is the probability it is NOT red?",
    options: ["1/3", "2/3", "3/4", "5/12"],
    answer: 1,
    explanation: "Not red = 3 + 5 = 8 marbles out of 12 total. Probability = 8/12 = 2/3.",
  },
  {
    id: "m024", section: "math", topic: "statistics", difficulty: "hard",
    question: "A population of bacteria triples every 3 hours. If there are 200 bacteria initially, how many will there be after 9 hours?",
    options: ["600", "1,800", "5,400", "16,200"],
    answer: 2,
    explanation: "After 3h: 600. After 6h: 1,800. After 9h: 5,400. (200 × 3³ = 200 × 27 = 5,400).",
  },
  {
    id: "m025", section: "math", topic: "statistics", difficulty: "medium",
    question: "A line of best fit predicts a student's score as 80. The student's actual score was 72. What is the residual for this student?",
    options: ["−8", "8", "−72", "152"],
    answer: 0,
    explanation: "Residual = actual − predicted = 72 − 80 = −8. A negative residual means the actual value is below the prediction.",
  },

  {
    id: "m075", section: "math", topic: "statistics", difficulty: "easy",
    question: "The mean of 4 numbers is 20. Three of the numbers are 15, 18, and 25. What is the fourth number?",
    options: ["18", "20", "22", "24"],
    answer: 2,
    explanation: "Total sum = 4 × 20 = 80. Known sum = 15 + 18 + 25 = 58. Fourth number = 80 − 58 = 22.",
  },
  {
    id: "m076", section: "math", topic: "statistics", difficulty: "medium",
    question: "A bag has 6 red, 4 blue, and 10 green marbles. What is the probability of drawing a blue marble?",
    options: ["1/5", "1/4", "2/5", "1/2"],
    answer: 0,
    explanation: "There are 20 total marbles and 4 are blue: 4/20 = 1/5.",
  },
  {
    id: "m077", section: "math", topic: "statistics", difficulty: "medium",
    question: "The data set {4, 7, 9, x, 15} is arranged in increasing order. If the median is 9, which of the following could be x?",
    options: ["6", "8", "12", "17"],
    answer: 2,
    explanation: "For the list to stay in increasing order with 9 as the middle (median) value, x must be between 9 and 15. Only 12 fits.",
  },
  {
    id: "m078", section: "math", topic: "statistics", difficulty: "hard",
    question: "A set of 5 test scores has a mean of 80. If the lowest score is removed, the mean of the remaining 4 scores becomes 85. What was the lowest score?",
    options: ["55", "60", "65", "70"],
    answer: 1,
    explanation: "Total of 5 scores = 400. Total of remaining 4 = 340. Lowest score = 400 − 340 = 60.",
  },
  {
    id: "m079", section: "math", topic: "statistics", difficulty: "easy",
    question: "A spinner has 8 equal sections numbered 1 through 8. What is the probability of landing on a number greater than 5?",
    options: ["1/8", "3/8", "1/2", "5/8"],
    answer: 1,
    explanation: "Numbers greater than 5 are 6, 7, 8 — three out of eight sections: 3/8.",
  },
  {
    id: "m080", section: "math", topic: "statistics", difficulty: "medium",
    question: "A line of best fit is given by y = 2x + 3. If a data point has x = 5 and an actual y-value of 16, what is the residual?",
    options: ["-3", "0", "3", "13"],
    answer: 2,
    explanation: "Predicted value = 2(5) + 3 = 13. Residual = actual − predicted = 16 − 13 = 3.",
  },
  {
    id: "m081", section: "math", topic: "statistics", difficulty: "medium",
    question: "A population of 500 bacteria doubles every 4 hours. How many bacteria will there be after 12 hours?",
    options: ["1500", "2000", "3000", "4000"],
    answer: 3,
    explanation: "12 hours is 3 doubling periods: 500 × 2³ = 500 × 8 = 4000.",
  },
  {
    id: "m082", section: "math", topic: "statistics", difficulty: "hard",
    question: "In a survey of 200 students, 120 play a sport and 90 play an instrument, with 40 doing both. How many students do neither?",
    options: ["20", "25", "30", "35"],
    answer: 2,
    explanation: "Students doing at least one = 120 + 90 − 40 = 170 (avoiding double-counting the overlap). Neither = 200 − 170 = 30.",
  },

  // ===== MATH: RATIOS & PERCENTAGES =====
  {
    id: "m026", section: "math", topic: "ratios", difficulty: "medium",
    question: "A jacket is discounted 20%, then discounted an additional 15% off the sale price. What is the total percent decrease from the original price?",
    options: ["32%", "35%", "30%", "28%"],
    answer: 0,
    explanation: "After 20% off: 80% remains. After 15% off that: 80% × 85% = 68%. Total decrease = 100% − 68% = 32%.",
  },
  {
    id: "m027", section: "math", topic: "ratios", difficulty: "medium",
    question: "If 40% of x equals 60% of 20, what is x?",
    options: ["12", "20", "30", "40"],
    answer: 2,
    explanation: "0.40x = 0.60 × 20 = 12 → x = 12 / 0.40 = 30.",
  },
  {
    id: "m028", section: "math", topic: "ratios", difficulty: "hard",
    question: "Two similar triangles have corresponding sides in the ratio 2:5. If the smaller triangle has area 8 cm², what is the area of the larger triangle?",
    options: ["20 cm²", "40 cm²", "50 cm²", "64 cm²"],
    answer: 2,
    explanation: "Area ratio = (side ratio)² = (2/5)² = 4/25. Larger area = 8 × (25/4) = 50 cm².",
  },
  {
    id: "m029", section: "math", topic: "ratios", difficulty: "hard",
    question: "The ratio of A to B is 3:4, and the ratio of B to C is 2:3. What is the ratio of A to C?",
    options: ["1:3", "1:2", "3:8", "2:3"],
    answer: 1,
    explanation: "A:B = 3:4, B:C = 2:3. Scale to common B: A:B = 3:4, B:C = 4:6. So A:B:C = 3:4:6. A:C = 3:6 = 1:2.",
  },

  {
    id: "m083", section: "math", topic: "ratios", difficulty: "easy",
    question: "If 3 apples cost $2.40, what is the cost of 5 apples?",
    options: ["$3.60", "$4.00", "$4.40", "$4.80"],
    answer: 1,
    explanation: "Unit price = $2.40 / 3 = $0.80. 5 apples = 5 × $0.80 = $4.00.",
  },
  {
    id: "m084", section: "math", topic: "ratios", difficulty: "medium",
    question: "A recipe requires 2 cups of flour for every 3 cups of sugar. If 9 cups of sugar are used, how many cups of flour are needed?",
    options: ["4", "5", "6", "7"],
    answer: 2,
    explanation: "The ratio 2:3 scales by 3 to 6:9, so 6 cups of flour are needed.",
  },
  {
    id: "m085", section: "math", topic: "ratios", difficulty: "medium",
    question: "A price increases from $80 to $92. What is the percent increase?",
    options: ["12%", "15%", "18%", "20%"],
    answer: 1,
    explanation: "Increase = 92 − 80 = 12. Percent increase = 12/80 = 0.15 = 15%.",
  },
  {
    id: "m086", section: "math", topic: "ratios", difficulty: "hard",
    question: "A map has a scale of 1 inch = 25 miles. If two cities are 7 inches apart on the map, how many miles apart are they in reality?",
    options: ["150", "160", "175", "200"],
    answer: 2,
    explanation: "7 × 25 = 175 miles.",
  },
  {
    id: "m087", section: "math", topic: "ratios", difficulty: "easy",
    question: "What is 30% of 150?",
    options: ["35", "40", "45", "50"],
    answer: 2,
    explanation: "0.30 × 150 = 45.",
  },
  {
    id: "m088", section: "math", topic: "ratios", difficulty: "medium",
    question: "A solution is 25% acid by volume. If there are 12 liters of acid in the solution, what is the total volume of the solution?",
    options: ["36", "42", "48", "54"],
    answer: 2,
    explanation: "12 liters is 25% of the total: total = 12 / 0.25 = 48 liters.",
  },
  {
    id: "m089", section: "math", topic: "ratios", difficulty: "hard",
    question: "Investment A earns $2000 at 6% simple annual interest. Investment B earns $1500 at x% simple annual interest. After one year, both investments earn the same amount of interest. What is x?",
    options: ["6%", "7%", "8%", "9%"],
    answer: 2,
    explanation: "Investment A earns 2000 × 0.06 = $120. Set 1500 × (x/100) = 120 → x = 12000/1500 = 8.",
  },
  {
    id: "m090", section: "math", topic: "ratios", difficulty: "medium",
    question: "The ratio of boys to girls in a class is 4:5. If there are 36 students total, how many are girls?",
    options: ["16", "18", "20", "22"],
    answer: 2,
    explanation: "The ratio 4:5 has 9 total parts. Each part = 36/9 = 4 students. Girls = 5 × 4 = 20.",
  },

  // ===== ENGLISH: GRAMMAR =====
  {
    id: "e001", section: "english", topic: "grammar", difficulty: "medium",
    question: "The jury, along with its alternates, _____ scheduled to deliberate this week.",
    options: ["is", "are", "have been", "were"],
    answer: 0,
    explanation: "The subject is 'jury' (singular). 'Along with its alternates' is a parenthetical phrase that doesn't change the subject's number. Use singular 'is.'",
  },
  {
    id: "e002", section: "english", topic: "grammar", difficulty: "medium",
    question: "Which sentence contains a comma splice?",
    options: [
      "The deadline passed; the report was never submitted.",
      "The deadline passed, the report was never submitted.",
      "The deadline passed, but the report was never submitted.",
      "The deadline passed. The report was never submitted.",
    ],
    answer: 1,
    explanation: "Option B joins two independent clauses with only a comma — this is a comma splice. Options A (semicolon), C (comma + coordinating conjunction), and D (period) are all correct.",
  },
  {
    id: "e003", section: "english", topic: "grammar", difficulty: "easy",
    question: "The professor expects students to complete readings, write essays, and _____ class discussions.",
    options: ["participating in", "to participate in", "participate in", "will participate in"],
    answer: 2,
    explanation: "The list uses base verb form: 'complete, write, participate.' Parallel structure requires 'participate in' to match the other verbs.",
  },
  {
    id: "e004", section: "english", topic: "grammar", difficulty: "medium",
    question: "By the time the guests arrived, the hosts _____ all the food.",
    options: ["prepared", "prepare", "have prepared", "had prepared"],
    answer: 3,
    explanation: "Past perfect ('had prepared') is used for an action completed before another past action ('arrived').",
  },
  {
    id: "e005", section: "english", topic: "grammar", difficulty: "medium",
    question: "Which sentence CORRECTLY places the modifier?",
    options: [
      "Running down the street, the wallet was found by Maria.",
      "Running down the street, Maria found the wallet.",
      "The wallet was found by Maria, running down the street.",
      "Running, the wallet was discovered by Maria on the street.",
    ],
    answer: 1,
    explanation: "The participial phrase 'Running down the street' must immediately precede the noun it modifies — Maria was running, not the wallet. Option B is correct.",
  },
  {
    id: "e006", section: "english", topic: "grammar", difficulty: "easy",
    question: "Which version correctly shows possession?",
    options: [
      "The childrens' books were scattered on the floor.",
      "The children's books were scattered on the floor.",
      "The childrens books were scattered on the floor.",
      "The children's book's were scattered on the floor.",
    ],
    answer: 1,
    explanation: "'Children' is already an irregular plural (not 'childrens'). To form its possessive, add 's: 'children's.'",
  },
  {
    id: "e007", section: "english", topic: "grammar", difficulty: "easy",
    question: "Which version is MOST concise without losing meaning?",
    options: [
      "Due to the fact that it was raining, the game was cancelled.",
      "Because it was raining, the game was cancelled.",
      "The game was cancelled owing to the precipitation that occurred.",
      "It was raining and for this reason the game got cancelled.",
    ],
    answer: 1,
    explanation: "'Because' is far more concise than 'Due to the fact that' while conveying the same causal meaning. SAT Writing consistently rewards concision.",
  },

  {
    id: "e027", section: "english", topic: "grammar", difficulty: "medium",
    question: "Each of the students _____ required to submit a project by Friday.",
    options: ["is", "are", "were", "have been"],
    answer: 0,
    explanation: "'Each' is a singular subject regardless of the plural noun that follows it. Use the singular verb 'is.'",
  },
  {
    id: "e028", section: "english", topic: "grammar", difficulty: "easy",
    question: "Neither the manager nor the employees _____ available for a meeting today.",
    options: ["is", "are", "was", "has been"],
    answer: 1,
    explanation: "In an 'either/or' or 'neither/nor' construction, the verb agrees with the subject closest to it — here, the plural 'employees,' so use 'are.'",
  },
  {
    id: "e029", section: "english", topic: "grammar", difficulty: "medium",
    question: "Give the award to _____ finishes the race first.",
    options: ["whoever", "whomever", "whoevers", "who"],
    answer: 0,
    explanation: "'Whoever' is the subject of the verb 'finishes,' so the subjective case is correct, not the objective 'whomever.'",
  },
  {
    id: "e030", section: "english", topic: "grammar", difficulty: "medium",
    question: "Which sentence has correct subject-verb agreement?",
    options: [
      "The list of items are on the table.",
      "The list of items is on the table.",
      "The lists of item is on the table.",
      "The list of items being on the table.",
    ],
    answer: 1,
    explanation: "The subject is the singular 'list,' not the plural 'items' in the prepositional phrase. Use the singular verb 'is.'",
  },
  {
    id: "e031", section: "english", topic: "grammar", difficulty: "easy",
    question: "Which sentence corrects the dangling modifier in 'Walking into the room, the lights were off'?",
    options: [
      "Walking into the room, the lights were off.",
      "Walking into the room, I noticed the lights were off.",
      "The lights were off, walking into the room.",
      "Walking into the room, off were the lights.",
    ],
    answer: 1,
    explanation: "The introductory phrase 'Walking into the room' must be followed by the person doing the walking — 'I' — not 'the lights.'",
  },
  {
    id: "e032", section: "english", topic: "grammar", difficulty: "medium",
    question: "Which sentence uses parallel structure correctly?",
    options: [
      "She enjoys hiking, to swim, and biking.",
      "She enjoys hiking, swimming, and biking.",
      "She enjoys to hike, swimming, and to bike.",
      "She enjoys hiking, swims, and biking.",
    ],
    answer: 1,
    explanation: "All items in the list must share the same grammatical form. 'Hiking, swimming, and biking' are all gerunds.",
  },
  {
    id: "e033", section: "english", topic: "grammar", difficulty: "medium",
    question: "Which sentence is punctuated correctly?",
    options: [
      "I wanted to leave early; however, the meeting ran long.",
      "I wanted to leave early, however the meeting ran long.",
      "I wanted to leave early; however the meeting, ran long.",
      "I wanted to leave early however; the meeting ran long.",
    ],
    answer: 0,
    explanation: "A semicolon correctly joins two independent clauses, and 'however' as a conjunctive adverb is followed by a comma.",
  },
  {
    id: "e034", section: "english", topic: "grammar", difficulty: "easy",
    question: "Which shows the correct possessive form for the plural noun 'students'?",
    options: ["the students's books", "the students' books", "the student's books", "the students books'"],
    answer: 1,
    explanation: "For a plural noun already ending in 's,' form the possessive by adding only an apostrophe: students'.",
  },
  {
    id: "e035", section: "english", topic: "grammar", difficulty: "hard",
    question: "Which sentence correctly describes an action that started in the past and continues into the present?",
    options: [
      "She has lived in Boston for ten years.",
      "She lived in Boston for ten years.",
      "She living in Boston for ten years.",
      "She will have lived in Boston for ten years.",
    ],
    answer: 0,
    explanation: "The present perfect tense ('has lived') is used for actions that began in the past and continue to the present.",
  },
  {
    id: "e036", section: "english", topic: "grammar", difficulty: "medium",
    question: "Which option avoids a sentence fragment?",
    options: [
      "Although the storm passed quickly.",
      "Although the storm passed quickly, the streets flooded.",
      "The storm. Passed quickly.",
      "Passed quickly, the storm.",
    ],
    answer: 1,
    explanation: "'Although the storm passed quickly' is a subordinate clause that needs an independent clause to complete the thought.",
  },

  // ===== ENGLISH: TRANSITIONS =====
  {
    id: "e008", section: "english", topic: "transitions", difficulty: "easy",
    question: "Cats are generally independent animals. _____, they often form strong bonds with their owners.",
    options: ["As a result", "Furthermore", "For example", "However"],
    answer: 3,
    explanation: "The second sentence presents a contrast (independence vs. bonding). 'However' signals a contrast or concession.",
  },
  {
    id: "e009", section: "english", topic: "transitions", difficulty: "easy",
    question: "The study found that regular exercise improves memory. _____, participants who exercised also reported significantly better sleep quality.",
    options: ["Nevertheless", "Moreover", "However", "In other words"],
    answer: 1,
    explanation: "The second sentence adds another benefit of exercise. 'Moreover' introduces an additional point that reinforces the first claim.",
  },
  {
    id: "e010", section: "english", topic: "transitions", difficulty: "medium",
    question: "The proposed bridge design is innovative. _____, engineers worry it may be too costly to build.",
    options: ["Similarly", "Therefore", "That said", "In addition"],
    answer: 2,
    explanation: "'That said' acknowledges the prior point (innovation) while introducing a counterargument (cost) — a concessive transition.",
  },
  {
    id: "e011", section: "english", topic: "transitions", difficulty: "easy",
    question: "The river flooded its banks after three days of heavy rain. _____, hundreds of residents were forced to evacuate.",
    options: ["In contrast", "Conversely", "As a result", "Regardless"],
    answer: 2,
    explanation: "The flooding caused the evacuation. 'As a result' signals a cause-and-effect relationship.",
  },
  {
    id: "e012", section: "english", topic: "transitions", difficulty: "easy",
    question: "Many scientific breakthroughs arose from unintended experiments. _____, penicillin was discovered when mold accidentally contaminated a petri dish.",
    options: ["However", "Instead", "For instance", "Therefore"],
    answer: 2,
    explanation: "Penicillin is a specific example of the general claim about unintended discoveries. 'For instance' introduces an illustrative example.",
  },

  {
    id: "e037", section: "english", topic: "transitions", difficulty: "easy",
    question: "The bridge has stood for over a century. _____, engineers recently found signs of structural wear.",
    options: ["Similarly", "Therefore", "However", "In addition"],
    answer: 2,
    explanation: "The second sentence contrasts with the bridge's long-standing reputation. 'However' signals that contrast.",
  },
  {
    id: "e038", section: "english", topic: "transitions", difficulty: "easy",
    question: "The company expanded into new markets. _____, it hired hundreds of new employees.",
    options: ["Nevertheless", "As a result", "In contrast", "Regardless"],
    answer: 1,
    explanation: "Hiring employees is a consequence of the expansion. 'As a result' signals cause and effect.",
  },
  {
    id: "e039", section: "english", topic: "transitions", difficulty: "medium",
    question: "The novel is set in the 1920s. _____, its themes about ambition remain relevant today.",
    options: ["Consequently", "Similarly", "Even so", "For example"],
    answer: 2,
    explanation: "'Even so' signals a concession — despite being set in the past, the novel's themes are still relevant now.",
  },
  {
    id: "e040", section: "english", topic: "transitions", difficulty: "easy",
    question: "Rainfall this year has been unusually low. _____, several reservoirs are at record-low levels.",
    options: ["However", "As a result", "In contrast", "Meanwhile"],
    answer: 1,
    explanation: "Low reservoir levels are a direct consequence of low rainfall. 'As a result' fits the cause-and-effect relationship.",
  },
  {
    id: "e041", section: "english", topic: "transitions", difficulty: "medium",
    question: "Some critics argue the film is overrated. _____, it won several major awards.",
    options: ["Similarly", "That said", "For example", "Therefore"],
    answer: 1,
    explanation: "'That said' introduces a concession or contrasting point after acknowledging the critics' view.",
  },
  {
    id: "e042", section: "english", topic: "transitions", difficulty: "easy",
    question: "The museum's new exhibit features ancient pottery. _____, it includes rare textiles from the same period.",
    options: ["However", "Additionally", "Nonetheless", "Conversely"],
    answer: 1,
    explanation: "The second sentence adds another feature of the exhibit. 'Additionally' signals this addition.",
  },
  {
    id: "e043", section: "english", topic: "transitions", difficulty: "medium",
    question: "Solar panel costs have dropped sharply. _____, adoption rates have risen across the country.",
    options: ["Consequently", "However", "Alternatively", "In contrast"],
    answer: 0,
    explanation: "Rising adoption is a direct result of falling costs. 'Consequently' signals cause and effect.",
  },
  {
    id: "e044", section: "english", topic: "transitions", difficulty: "hard",
    question: "Many assumed the small startup would fail within a year. _____, it became one of the industry's fastest-growing companies.",
    options: ["Similarly", "Instead", "Furthermore", "Consequently"],
    answer: 1,
    explanation: "'Instead' signals that the actual outcome contradicted the expectation described in the first sentence.",
  },

  // ===== ENGLISH: VOCABULARY IN CONTEXT =====
  {
    id: "e013", section: "english", topic: "vocabulary", difficulty: "easy",
    question: "The politician's speech was deliberately opaque, making it difficult for the audience to understand her true position. As used in context, 'opaque' most nearly means:",
    options: ["transparent", "unclear", "powerful", "lengthy"],
    answer: 1,
    explanation: "The context clue 'making it difficult to understand' signals that 'opaque' means unclear or obscure.",
  },
  {
    id: "e014", section: "english", topic: "vocabulary", difficulty: "easy",
    question: "The scientist's tenacious pursuit of the answer led her to run more than 400 experiments before finding a solution. As used in context, 'tenacious' most nearly means:",
    options: ["casual", "brief", "persistent", "collaborative"],
    answer: 2,
    explanation: "Running 400+ experiments suggests unwavering determination. 'Tenacious' means stubbornly persistent.",
  },
  {
    id: "e015", section: "english", topic: "vocabulary", difficulty: "medium",
    question: "The critic called the novel derivative, arguing it offered nothing original to the genre. As used in context, 'derivative' most nearly means:",
    options: ["innovative", "mathematical", "unoriginal", "complex"],
    answer: 2,
    explanation: "'Nothing original' in the same sentence clarifies that 'derivative' here means lacking originality — borrowed from or based on others' work.",
  },
  {
    id: "e016", section: "english", topic: "vocabulary", difficulty: "easy",
    question: "Her candid assessment of the team's weaknesses surprised those who expected more diplomatic feedback. As used in context, 'candid' most nearly means:",
    options: ["harsh", "photographed", "lengthy", "honest"],
    answer: 3,
    explanation: "Contrasted with 'diplomatic,' 'candid' implies straightforward, unfiltered honesty.",
  },
  {
    id: "e017", section: "english", topic: "vocabulary", difficulty: "medium",
    question: "The architect's plan was considered audacious by those who said it was impossibly ambitious. As used in context, 'audacious' most nearly means:",
    options: ["modest", "bold", "flawed", "careful"],
    answer: 1,
    explanation: "'Impossibly ambitious' signals extreme daring. 'Audacious' means boldly daring or fearlessly ambitious.",
  },

  {
    id: "e045", section: "english", topic: "vocabulary", difficulty: "easy",
    question: "The committee's decision was unanimous, leaving no room for further debate. As used in context, 'unanimous' most nearly means:",
    options: ["divided", "agreed by all", "delayed", "controversial"],
    answer: 1,
    explanation: "'Leaving no room for further debate' signals total agreement — 'unanimous' means agreed by everyone.",
  },
  {
    id: "e046", section: "english", topic: "vocabulary", difficulty: "easy",
    question: "His terse reply suggested he did not want to discuss the matter further. As used in context, 'terse' most nearly means:",
    options: ["lengthy", "brief and curt", "friendly", "confused"],
    answer: 1,
    explanation: "A reply signaling reluctance to discuss further would be short and clipped — 'terse' means brief and curt.",
  },
  {
    id: "e047", section: "english", topic: "vocabulary", difficulty: "medium",
    question: "The company's ambiguous statement left investors uncertain about its future plans. As used in context, 'ambiguous' most nearly means:",
    options: ["clear", "unclear", "encouraging", "financial"],
    answer: 1,
    explanation: "'Left investors uncertain' signals that the statement was unclear or open to multiple interpretations.",
  },
  {
    id: "e048", section: "english", topic: "vocabulary", difficulty: "medium",
    question: "Despite the setback, she remained resilient and quickly adapted her strategy. As used in context, 'resilient' most nearly means:",
    options: ["discouraged", "able to recover quickly", "indifferent", "stubborn"],
    answer: 1,
    explanation: "'Despite the setback' and 'quickly adapted' both signal an ability to recover from difficulty.",
  },
  {
    id: "e049", section: "english", topic: "vocabulary", difficulty: "easy",
    question: "The professor's meticulous notes left nothing to chance. As used in context, 'meticulous' most nearly means:",
    options: ["careless", "extremely careful", "brief", "outdated"],
    answer: 1,
    explanation: "'Left nothing to chance' indicates extreme care and attention to detail.",
  },
  {
    id: "e050", section: "english", topic: "vocabulary", difficulty: "medium",
    question: "The critic praised the film's understated performances, which conveyed emotion without excess. As used in context, 'understated' most nearly means:",
    options: ["exaggerated", "subtle", "loud", "confusing"],
    answer: 1,
    explanation: "'Without excess' signals restraint — 'understated' means subtle or not exaggerated.",
  },
  {
    id: "e051", section: "english", topic: "vocabulary", difficulty: "hard",
    question: "The senator's equivocal answer avoided taking a clear position. As used in context, 'equivocal' most nearly means:",
    options: ["deceptive in a vague way", "honest", "enthusiastic", "detailed"],
    answer: 0,
    explanation: "'Avoided taking a clear position' signals deliberate vagueness — 'equivocal' means ambiguous or evasive.",
  },
  {
    id: "e052", section: "english", topic: "vocabulary", difficulty: "medium",
    question: "The old bridge, though dilapidated, still attracted tourists. As used in context, 'dilapidated' most nearly means:",
    options: ["newly built", "run-down", "colorful", "expensive"],
    answer: 1,
    explanation: "'Though dilapidated' contrasts with still attracting tourists, implying the bridge is old and run-down.",
  },

  // ===== ENGLISH: READING COMPREHENSION (Passage 1) =====
  {
    id: "e018", section: "english", topic: "reading", difficulty: "medium",
    passage: "Urban heat islands occur when cities are significantly warmer than surrounding rural areas. Dark surfaces such as asphalt and concrete absorb more solar radiation than vegetation, releasing this heat in the evenings. Cities can be 2–5°C warmer than nearby areas, with the effect most pronounced during summer nights. Urban planners increasingly advocate for green infrastructure—parks, green roofs, and tree-lined streets—as a cost-effective strategy to reduce these temperature differences.",
    question: "What is the primary purpose of this passage?",
    options: [
      "To argue that rural areas are more comfortable than cities",
      "To explain urban heat islands and describe a potential solution",
      "To warn readers about the dangers of asphalt surfaces",
      "To describe how solar radiation damages city infrastructure",
    ],
    answer: 1,
    explanation: "The passage defines urban heat islands (cause/effect) and then proposes green infrastructure as a solution. Option B is the most accurate summary of the passage's full scope.",
  },
  {
    id: "e019", section: "english", topic: "reading", difficulty: "easy",
    passage: "Urban heat islands occur when cities are significantly warmer than surrounding rural areas. Dark surfaces such as asphalt and concrete absorb more solar radiation than vegetation, releasing this heat in the evenings. Cities can be 2–5°C warmer than nearby areas, with the effect most pronounced during summer nights. Urban planners increasingly advocate for green infrastructure—parks, green roofs, and tree-lined streets—as a cost-effective strategy to reduce these temperature differences.",
    question: "According to the passage, when is the urban heat island effect most pronounced?",
    options: ["Winter daytime hours", "Spring evenings", "Summer nights", "Rainy weather"],
    answer: 2,
    explanation: "The passage states the effect is 'most pronounced during summer nights.'",
  },
  {
    id: "e020", section: "english", topic: "reading", difficulty: "medium",
    passage: "Urban heat islands occur when cities are significantly warmer than surrounding rural areas. Dark surfaces such as asphalt and concrete absorb more solar radiation than vegetation, releasing this heat in the evenings. Cities can be 2–5°C warmer than nearby areas, with the effect most pronounced during summer nights. Urban planners increasingly advocate for green infrastructure—parks, green roofs, and tree-lined streets—as a cost-effective strategy to reduce these temperature differences.",
    question: "Based on the passage, which action would most likely REDUCE the urban heat island effect?",
    options: [
      "Paving more pedestrian areas with dark asphalt",
      "Replacing a vacant lot with a community garden",
      "Widening highways to reduce traffic congestion",
      "Installing dark-colored roofing tiles on buildings",
    ],
    answer: 1,
    explanation: "The passage says green infrastructure (parks, trees) reduces the effect. A community garden adds vegetation, lowering heat absorption. Options A and D increase dark surfaces.",
  },

  // ===== ENGLISH: READING COMPREHENSION (Passage 2) =====
  {
    id: "e021", section: "english", topic: "reading", difficulty: "medium",
    passage: "When Mount Vesuvius erupted in 79 AD, it buried the ancient city of Pompeii under volcanic ash and pumice. For nearly 1,700 years, the city lay hidden beneath the surface. When excavations began in the 18th century, archaeologists found remarkably preserved buildings, artwork, and even food. These discoveries have given historians extraordinary insight into daily Roman life—from graffiti scratched on walls to loaves of carbonized bread still sitting in bakeries.",
    question: "How is this passage primarily organized?",
    options: [
      "Comparison between Pompeii and other Roman cities",
      "Chronological account of events followed by their significance",
      "A series of arguments supporting archaeological funding",
      "Problem and solution structure",
    ],
    answer: 1,
    explanation: "The passage moves through time (eruption → burial → excavation) and then explains the significance of the findings — a chronological structure followed by discussion of impact.",
  },
  {
    id: "e022", section: "english", topic: "reading", difficulty: "easy",
    passage: "When Mount Vesuvius erupted in 79 AD, it buried the ancient city of Pompeii under volcanic ash and pumice. For nearly 1,700 years, the city lay hidden beneath the surface. When excavations began in the 18th century, archaeologists found remarkably preserved buildings, artwork, and even food. These discoveries have given historians extraordinary insight into daily Roman life—from graffiti scratched on walls to loaves of carbonized bread still sitting in bakeries.",
    question: "Which detail from the passage BEST supports the claim that Pompeii provides insight into everyday Roman life?",
    options: [
      "The eruption occurred in 79 AD",
      "Excavations began in the 18th century",
      "Graffiti on walls and bread in bakeries were preserved",
      "Mount Vesuvius buried the city under ash and pumice",
    ],
    answer: 2,
    explanation: "Graffiti and bread in bakeries are examples of ordinary daily objects. They directly support the claim about insight into everyday life. The other options are historical facts that don't illustrate daily life specifically.",
  },
  {
    id: "e023", section: "english", topic: "reading", difficulty: "medium",
    passage: "When Mount Vesuvius erupted in 79 AD, it buried the ancient city of Pompeii under volcanic ash and pumice. For nearly 1,700 years, the city lay hidden beneath the surface. When excavations began in the 18th century, archaeologists found remarkably preserved buildings, artwork, and even food. These discoveries have given historians extraordinary insight into daily Roman life—from graffiti scratched on walls to loaves of carbonized bread still sitting in bakeries.",
    question: "Based on the passage, what can be inferred about Pompeii's preserved items?",
    options: [
      "Most artifacts were damaged beyond recognition",
      "Only stone structures survived the eruption",
      "Volcanic ash encased the city rapidly, preserving ordinary objects in unusual detail",
      "Excavations destroyed most of the original site",
    ],
    answer: 2,
    explanation: "The passage describes bread, artwork, and graffiti as 'remarkably preserved,' implying the rapid burial in ash protected items that would normally decay.",
  },

  // ===== ENGLISH: READING COMPREHENSION (Passage 3) =====
  {
    id: "e053", section: "english", topic: "reading", difficulty: "medium",
    passage: "Coral reefs, often called the rainforests of the sea, support roughly a quarter of all marine species despite covering less than one percent of the ocean floor. Rising ocean temperatures cause coral bleaching, a process in which corals expel the algae living in their tissues, turning white and losing a vital energy source. While bleached coral can recover if temperatures drop quickly, repeated or prolonged bleaching events often lead to coral death. Marine biologists are now cultivating heat-resistant coral strains in laboratories, hoping to replant them in damaged reefs before further warming occurs.",
    question: "What is the primary purpose of this passage?",
    options: [
      "To criticize marine biologists for slow progress",
      "To explain coral bleaching and a proposed response to it",
      "To argue that coral reefs are unimportant to marine life",
      "To describe the physical location of coral reefs",
    ],
    answer: 1,
    explanation: "The passage defines coral bleaching (cause and process) and then describes an effort by marine biologists to counter it — explanation plus proposed response.",
  },
  {
    id: "e054", section: "english", topic: "reading", difficulty: "easy",
    passage: "Coral reefs, often called the rainforests of the sea, support roughly a quarter of all marine species despite covering less than one percent of the ocean floor. Rising ocean temperatures cause coral bleaching, a process in which corals expel the algae living in their tissues, turning white and losing a vital energy source. While bleached coral can recover if temperatures drop quickly, repeated or prolonged bleaching events often lead to coral death. Marine biologists are now cultivating heat-resistant coral strains in laboratories, hoping to replant them in damaged reefs before further warming occurs.",
    question: "According to the passage, what percentage of the ocean floor do coral reefs cover?",
    options: ["About 1%", "About 10%", "About 25%", "About 50%"],
    answer: 0,
    explanation: "The passage states reefs cover 'less than one percent of the ocean floor.'",
  },
  {
    id: "e055", section: "english", topic: "reading", difficulty: "medium",
    passage: "Coral reefs, often called the rainforests of the sea, support roughly a quarter of all marine species despite covering less than one percent of the ocean floor. Rising ocean temperatures cause coral bleaching, a process in which corals expel the algae living in their tissues, turning white and losing a vital energy source. While bleached coral can recover if temperatures drop quickly, repeated or prolonged bleaching events often lead to coral death. Marine biologists are now cultivating heat-resistant coral strains in laboratories, hoping to replant them in damaged reefs before further warming occurs.",
    question: "Based on the passage, what happens during coral bleaching?",
    options: [
      "Coral absorbs more algae than usual",
      "Coral expels algae and loses a key energy source",
      "Coral reproduces at a faster rate",
      "Coral becomes more resistant to heat",
    ],
    answer: 1,
    explanation: "The passage states that during bleaching, 'corals expel the algae living in their tissues... losing a vital energy source.'",
  },
  {
    id: "e056", section: "english", topic: "reading", difficulty: "medium",
    passage: "Coral reefs, often called the rainforests of the sea, support roughly a quarter of all marine species despite covering less than one percent of the ocean floor. Rising ocean temperatures cause coral bleaching, a process in which corals expel the algae living in their tissues, turning white and losing a vital energy source. While bleached coral can recover if temperatures drop quickly, repeated or prolonged bleaching events often lead to coral death. Marine biologists are now cultivating heat-resistant coral strains in laboratories, hoping to replant them in damaged reefs before further warming occurs.",
    question: "Which detail best supports the claim that coral reefs are important to marine biodiversity?",
    options: [
      "Reefs cover less than 1% of the ocean floor",
      "Reefs support about a quarter of all marine species",
      "Coral can recover if temperatures drop",
      "Scientists are cultivating new coral strains",
    ],
    answer: 1,
    explanation: "Supporting about a quarter of all marine species directly demonstrates the reefs' outsized importance to biodiversity.",
  },
  {
    id: "e057", section: "english", topic: "reading", difficulty: "hard",
    passage: "Coral reefs, often called the rainforests of the sea, support roughly a quarter of all marine species despite covering less than one percent of the ocean floor. Rising ocean temperatures cause coral bleaching, a process in which corals expel the algae living in their tissues, turning white and losing a vital energy source. While bleached coral can recover if temperatures drop quickly, repeated or prolonged bleaching events often lead to coral death. Marine biologists are now cultivating heat-resistant coral strains in laboratories, hoping to replant them in damaged reefs before further warming occurs.",
    question: "What can be inferred about the marine biologists' lab efforts?",
    options: [
      "They have already stopped ocean warming",
      "They aim to preemptively counter future bleaching events",
      "They believe coral reefs cannot be saved",
      "They focus only on documenting reef decline",
    ],
    answer: 1,
    explanation: "The passage says biologists hope to replant heat-resistant coral 'before further warming occurs' — a preemptive strategy against future bleaching.",
  },
  {
    id: "e058", section: "english", topic: "reading", difficulty: "easy",
    passage: "Coral reefs, often called the rainforests of the sea, support roughly a quarter of all marine species despite covering less than one percent of the ocean floor. Rising ocean temperatures cause coral bleaching, a process in which corals expel the algae living in their tissues, turning white and losing a vital energy source. While bleached coral can recover if temperatures drop quickly, repeated or prolonged bleaching events often lead to coral death. Marine biologists are now cultivating heat-resistant coral strains in laboratories, hoping to replant them in damaged reefs before further warming occurs.",
    question: "Which word from the passage most nearly means 'lasting for a long time'?",
    options: ["Rising", "Prolonged", "Vital", "Damaged"],
    answer: 1,
    explanation: "'Prolonged' describes bleaching events that last an extended time, contrasted with brief ones the coral can recover from.",
  },

  // ===== ENGLISH: RHETORICAL SYNTHESIS =====
  {
    id: "e024", section: "english", topic: "synthesis", difficulty: "hard",
    passage: "Source 1: Students who sleep 8 or more hours per night perform significantly better on cognitive tests.\nSource 2: Schools that start at 8:30 AM or later report higher attendance rates and improved academic performance.",
    question: "Which statement best uses BOTH sources to argue that school start times affect student learning?",
    options: [
      "Sleep is important for students, and many students do not get enough of it.",
      "Later school start times allow students to get more sleep, which research links to better cognitive performance and attendance.",
      "Many schools begin before 8 AM, which is inconvenient for working families.",
      "Students who sleep more tend to perform better on cognitive tests.",
    ],
    answer: 1,
    explanation: "Option B integrates both sources: later start times (Source 2) allow more sleep, which improves cognitive performance (Source 1). It's the only answer that draws on both sources to support the specific claim.",
  },
  {
    id: "e025", section: "english", topic: "synthesis", difficulty: "hard",
    passage: "Source 1: Taking handwritten notes engages different neural pathways than typing, activating areas linked to memory and comprehension.\nSource 2: Students who write notes by hand tend to paraphrase information rather than transcribe it verbatim, leading to deeper processing.",
    question: "Which statement best synthesizes BOTH sources to argue that handwriting improves learning?",
    options: [
      "Typing is more efficient than handwriting for most students.",
      "Handwriting activates memory-linked neural pathways and encourages paraphrasing, both of which support deeper learning.",
      "Students should always write by hand instead of using computers.",
      "Neural pathways are engaged during all forms of note-taking.",
    ],
    answer: 1,
    explanation: "Option B integrates the neural benefit (Source 1) and the paraphrasing effect (Source 2) into a unified argument about handwriting improving learning.",
  },
  {
    id: "e026", section: "english", topic: "synthesis", difficulty: "medium",
    passage: "In a study of 500 students, 65% of those who used flashcards scored above 600 on SAT Math, compared to 40% of students who did not use flashcards.",
    question: "Which conclusion is BEST supported by this data?",
    options: [
      "Flashcards cause students to score above 600 on the SAT.",
      "Students who used flashcards were more likely to score above 600 than those who did not.",
      "All students should use flashcards to prepare for the SAT.",
      "SAT Math performance is entirely determined by study tools used.",
    ],
    answer: 1,
    explanation: "The data shows correlation (more flashcard users scored above 600), not causation. Option B accurately reflects what the data shows without overstating it.",
  },
  {
    id: "e059", section: "english", topic: "synthesis", difficulty: "hard",
    passage: "Source 1: Cities with more public parks report higher resident satisfaction and lower stress levels.\nSource 2: Access to green space has been linked to reduced rates of certain chronic illnesses.",
    question: "Which statement best uses BOTH sources to argue that urban parks improve public health and well-being?",
    options: [
      "Parks make cities look more attractive.",
      "Increasing access to green space in cities can boost residents' well-being and reduce chronic illness rates.",
      "Some cities have more parks than others.",
      "Chronic illness is unrelated to city planning.",
    ],
    answer: 1,
    explanation: "Option B combines the well-being benefit (Source 1) and the chronic-illness benefit (Source 2) into one argument about green space improving public health.",
  },
  {
    id: "e060", section: "english", topic: "synthesis", difficulty: "hard",
    passage: "Source 1: Students who receive immediate feedback on assignments show faster skill improvement.\nSource 2: Delayed feedback is associated with students forgetting the specific errors they made.",
    question: "Which statement best synthesizes BOTH sources to argue for prompt feedback in education?",
    options: [
      "Feedback is not necessary for learning.",
      "Students always forget their mistakes.",
      "Providing feedback quickly helps students retain and correct specific errors, speeding up skill improvement.",
      "Delayed feedback is preferred by most teachers.",
    ],
    answer: 2,
    explanation: "Option C integrates the retention benefit (Source 2, avoiding forgotten errors) with the improvement benefit (Source 1) of immediate feedback.",
  },
  {
    id: "e061", section: "english", topic: "synthesis", difficulty: "medium",
    passage: "In a survey of 300 employees, 70% of those who worked remotely at least twice a week reported high job satisfaction, compared to 45% of employees who worked in-office full time.",
    question: "Which conclusion is BEST supported by this data?",
    options: [
      "Remote work causes higher job satisfaction.",
      "Employees who worked remotely at least twice a week were more likely to report high satisfaction than full-time in-office employees.",
      "All employees should work remotely.",
      "In-office employees are less productive.",
    ],
    answer: 1,
    explanation: "The data shows a correlation between remote work frequency and reported satisfaction, not causation or a productivity claim. Option B states only what the data shows.",
  },
  {
    id: "e062", section: "english", topic: "synthesis", difficulty: "medium",
    passage: "Source 1: Regular exercise has been shown to improve short-term memory in adults.\nSource 2: Adults who exercise regularly also report better sleep quality.",
    question: "Which statement best uses BOTH sources to support the idea that exercise benefits cognitive health both directly and indirectly?",
    options: [
      "Exercise is enjoyable for most adults.",
      "Exercise improves memory directly and may also support cognitive health indirectly by improving sleep quality.",
      "Sleep quality has no connection to exercise.",
      "Only young adults benefit from exercise.",
    ],
    answer: 1,
    explanation: "Option B combines the direct memory benefit (Source 1) with the indirect sleep-quality benefit (Source 2) to support the dual-pathway claim.",
  },
];

export function getQuestions(section?: "math" | "english", topic?: string): Question[] {
  return QUESTIONS.filter(
    (q) =>
      (!section || q.section === section) &&
      (!topic || q.topic === topic)
  );
}

export function shuffled(arr: Question[]): Question[] {
  return [...arr].sort(() => Math.random() - 0.5);
}

export function pickRandom(section?: "math" | "english", topic?: string, count = 1): Question[] {
  const pool = shuffled(getQuestions(section, topic));
  return pool.slice(0, Math.min(count, pool.length));
}
